name: FNF Porter Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            icon: icon.ico
            ext: .exe
          - os: macos-latest
            icon: icon.icns
            ext: 
          - os: ubuntu-latest
            icon: ""
            ext: 

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller numpy pydub luaparser pyqt6 pillow
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile psychtobase/main.py --icon=${{ matrix.icon }} --noconsole -n "FNF Porter actions-${{ github.run_number }}"
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: FNF_Porter_Build_${{ matrix.os }}
        path: dist/*${{ matrix.ext }}
